from algorithm.config import (
    EMBEDDING_MODEL,
    IMAGE_PROFILE_MODEL,
    MIN_ENTRIES_FOR_PERSONALIZATION,
    MIN_SIMILAR_USERS,
    ML_PROVIDER,
    RECOMMENDATION_COOLDOWN_REQUESTS,
    RECOMMENDATION_LIMIT,
    RECOMMENDATION_SCORE_WEIGHTS,
    SHORT_TERM_ENTRY_COUNT,
    SIMILAR_USER_THRESHOLD,
    TEXT_PROFILE_MODEL,
)
from algorithm.contract import generate_recommendations, generate_taste_report
from algorithm.entry_profiling import profile_diary_entry
from algorithm.schemas import (
    DiaryEntryInput,
    EntryProfileArtifact,
    RecommendationArtifact,
    RecommendationContext,
    RecommendedResponse,
    RecommendedRestaurant,
    RestaurantInput,
    RestaurantProfileArtifact,
    ScoredRecommendationArtifact,
    SyntheticFixtureSet,
    SyntheticUser,
    TasteProfileInsufficient,
    TasteProfileReady,
    TasteProfileResponse,
    UserProfileArtifact,
)
from algorithm.version import ALGORITHM_VERSION, __version__


__all__ = [
    "ALGORITHM_VERSION",
    "DiaryEntryInput",
    "EMBEDDING_MODEL",
    "EntryProfileArtifact",
    "IMAGE_PROFILE_MODEL",
    "MIN_ENTRIES_FOR_PERSONALIZATION",
    "MIN_SIMILAR_USERS",
    "ML_PROVIDER",
    "RecommendationArtifact",
    "RecommendationContext",
    "RECOMMENDATION_COOLDOWN_REQUESTS",
    "RECOMMENDATION_LIMIT",
    "RECOMMENDATION_SCORE_WEIGHTS",
    "RecommendedResponse",
    "RecommendedRestaurant",
    "RestaurantInput",
    "RestaurantProfileArtifact",
    "SHORT_TERM_ENTRY_COUNT",
    "SIMILAR_USER_THRESHOLD",
    "ScoredRecommendationArtifact",
    "SyntheticFixtureSet",
    "SyntheticUser",
    "TasteProfileInsufficient",
    "TasteProfileReady",
    "TasteProfileResponse",
    "TEXT_PROFILE_MODEL",
    "UserProfileArtifact",
    "__version__",
    "generate_recommendations",
    "generate_taste_report",
    "profile_diary_entry",
]
