from app.config.algorithm import (
    ALGORITHM_VERSION,
    EMBEDDING_DIMENSIONS,
    EMBEDDING_MODEL,
    IMAGE_PROFILE_MODEL,
    MIN_ENTRIES_FOR_PERSONALIZATION,
    MIN_SIMILAR_USERS,
    RECOMMENDATION_COOLDOWN_REQUESTS,
    RECOMMENDATION_LIMIT,
    RECOMMENDATION_SCORE_WEIGHTS,
    SHORT_TERM_ENTRY_COUNT,
    SIMILAR_USER_THRESHOLD,
    SUMMARY_MODEL,
    TEXT_PROFILE_MODEL,
    __version__,
)
from app.schemas.algorithm import (
    DiaryEntryInput,
    EntryProfileArtifact,
    KakaoRestaurantMetadata,
    ProfileExtractionResult,
    ProfileSummaryResult,
    RecommendationArtifact,
    RecommendationContext,
    RecommendationScoreBreakdown,
    RecommendedResponse,
    RecommendedRestaurant,
    RestaurantInput,
    RestaurantProfileArtifact,
    ScoredRecommendationArtifact,
    TasteProfileInsufficient,
    TasteProfileReady,
    TasteProfileResponse,
    UserProfileArtifact,
)
from app.services.algorithm.entry_profiling import profile_diary_entry
from app.services.algorithm.providers import DeterministicProvider, OpenAIProvider, ProfileProvider
from app.services.algorithm.recommendation_engine import (
    generate_recommendation_artifact,
    generate_recommendations,
)
from app.services.algorithm.restaurant_profiling import profile_kakao_restaurant
from app.services.algorithm.taste_report import generate_taste_report
from app.services.algorithm.user_profiling import (
    aggregate_user_profile,
    build_weighted_entry_profiles,
)

__all__ = [
    "ALGORITHM_VERSION",
    "DeterministicProvider",
    "DiaryEntryInput",
    "EMBEDDING_DIMENSIONS",
    "EMBEDDING_MODEL",
    "EntryProfileArtifact",
    "IMAGE_PROFILE_MODEL",
    "KakaoRestaurantMetadata",
    "MIN_ENTRIES_FOR_PERSONALIZATION",
    "MIN_SIMILAR_USERS",
    "OpenAIProvider",
    "ProfileExtractionResult",
    "ProfileProvider",
    "ProfileSummaryResult",
    "RecommendationArtifact",
    "RecommendationContext",
    "RecommendationScoreBreakdown",
    "RECOMMENDATION_COOLDOWN_REQUESTS",
    "RECOMMENDATION_LIMIT",
    "RECOMMENDATION_SCORE_WEIGHTS",
    "RecommendedResponse",
    "RecommendedRestaurant",
    "RestaurantInput",
    "RestaurantProfileArtifact",
    "SHORT_TERM_ENTRY_COUNT",
    "SIMILAR_USER_THRESHOLD",
    "SUMMARY_MODEL",
    "ScoredRecommendationArtifact",
    "TasteProfileInsufficient",
    "TasteProfileReady",
    "TasteProfileResponse",
    "TEXT_PROFILE_MODEL",
    "UserProfileArtifact",
    "__version__",
    "aggregate_user_profile",
    "build_weighted_entry_profiles",
    "generate_recommendation_artifact",
    "generate_recommendations",
    "generate_taste_report",
    "profile_diary_entry",
    "profile_kakao_restaurant",
]
